# Generated by Django 6.0.4 on 2026-04-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0002_rota_destino_lat_rota_destino_lng_alter_rota_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCompartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_compartimentos', to='fretes.carga')),
                ('compartimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretes.compartimento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fretes.produto')),
            ],
            options={
                'verbose_name': 'Compartimento da Carga',
                'verbose_name_plural': 'Compartimentos da Carga',
                'ordering': ['compartimento__numero'],
                'unique_together': {('carga', 'compartimento')},
            },
        ),
    ]
