# Generated by Django 6.0.4 on 2026-04-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0009_alter_carga_cliente_cargacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.cliente'),
        ),
    ]
