# Generated by Django 6.0.4 on 2026-04-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0010_alter_carga_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacompartimento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fretes.cliente'),
        ),
    ]
