# Generated by Django 6.0.4 on 2026-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0011_add_cliente_to_carga_compartimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='parada_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_6',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_7',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rota',
            name='tempo_total_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo total (min)'),
        ),
    ]
