# Generated by Django 6.0.4 on 2026-04-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0012_rota_paradas_tempo_total'),
    ]

    operations = [
        # Remover campos CharField antigos
        migrations.RemoveField(model_name='rota', name='parada_1'),
        migrations.RemoveField(model_name='rota', name='parada_2'),
        migrations.RemoveField(model_name='rota', name='parada_3'),
        migrations.RemoveField(model_name='rota', name='parada_4'),
        migrations.RemoveField(model_name='rota', name='parada_5'),
        migrations.RemoveField(model_name='rota', name='parada_6'),
        migrations.RemoveField(model_name='rota', name='parada_7'),
        # Adicionar campos ForeignKey novos
        migrations.AddField(
            model_name='rota',
            name='parada_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 1'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 2'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 3'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 4'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 5'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 6'),
        ),
        migrations.AddField(
            model_name='rota',
            name='parada_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fretes.cliente', verbose_name='Parada 7'),
        ),
    ]
