# Generated by Django 6.0.4 on 2026-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0013_alter_rota_parada_1_alter_rota_parada_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhao',
            name='ano_fabricacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de fabricação'),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='tipo_eixo',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('bi_truck', 'Bi Truck'), ('carreta', 'Carreta')], max_length=20, verbose_name='Tipo do eixo'),
        ),
    ]
