# Generated by Django 6.0.4 on 2026-04-16 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0014_caminhao_ano_fabricacao_caminhao_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('pneus', 'Pneus'), ('eletrica', 'Elétrica'), ('funilaria', 'Funilaria'), ('outros', 'Outros')], max_length=30)),
                ('descricao', models.TextField()),
                ('data_servico', models.DateField(default=django.utils.timezone.localdate)),
                ('km_atual', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM atual')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oficina', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='fretes.caminhao')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_servico', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('posicao', models.CharField(choices=[('DE', 'Dianteiro Esquerdo'), ('DD', 'Dianteiro Direito'), ('TEI', 'Traseiro Esquerdo Interno'), ('TEE', 'Traseiro Esquerdo Externo'), ('TDI', 'Traseiro Direito Interno'), ('TDE', 'Traseiro Direito Externo'), ('E1', 'Eixo 2 Esquerdo Interno'), ('E2', 'Eixo 2 Esquerdo Externo'), ('E3', 'Eixo 2 Direito Interno'), ('E4', 'Eixo 2 Direito Externo'), ('E5', 'Eixo 3 Esquerdo Interno'), ('E6', 'Eixo 3 Esquerdo Externo'), ('E7', 'Eixo 3 Direito Interno'), ('E8', 'Eixo 3 Direito Externo'), ('estepe', 'Estepe')], max_length=10, verbose_name='Posição')),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('numero_fogo', models.CharField(blank=True, max_length=50, verbose_name='Número de fogo (DOT)')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de instalação')),
                ('km_instalacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na instalação')),
                ('sulco_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Sulco (mm)')),
                ('recapado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus', to='fretes.caminhao')),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'ordering': ['caminhao__placa', 'posicao'],
            },
        ),
    ]
