# Generated by Django 6.0.4 on 2026-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0015_manutencao_pneu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneu',
            name='status',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atenção'), ('ruim', 'Ruim')], default='bom', max_length=10),
        ),
        migrations.AlterField(
            model_name='pneu',
            name='posicao',
            field=models.CharField(choices=[('1E', '1° Eixo – Esquerdo'), ('1D', '1° Eixo – Direito'), ('2E', '2° Eixo – Esquerdo'), ('2D', '2° Eixo – Direito'), ('2EI', '2° Eixo – Esq. Interno'), ('2EE', '2° Eixo – Esq. Externo'), ('2DI', '2° Eixo – Dir. Interno'), ('2DE', '2° Eixo – Dir. Externo'), ('3EI', '3° Eixo – Esq. Interno'), ('3EE', '3° Eixo – Esq. Externo'), ('3DI', '3° Eixo – Dir. Interno'), ('3DE', '3° Eixo – Dir. Externo'), ('4EI', '4° Eixo – Esq. Interno'), ('4EE', '4° Eixo – Esq. Externo'), ('4DI', '4° Eixo – Dir. Interno'), ('4DE', '4° Eixo – Dir. Externo'), ('5EI', '5° Eixo – Esq. Interno'), ('5EE', '5° Eixo – Esq. Externo'), ('5DI', '5° Eixo – Dir. Interno'), ('5DE', '5° Eixo – Dir. Externo'), ('6EI', '6° Eixo – Esq. Interno'), ('6EE', '6° Eixo – Esq. Externo'), ('6DI', '6° Eixo – Dir. Interno'), ('6DE', '6° Eixo – Dir. Externo'), ('ESP', 'Estepe')], max_length=10, verbose_name='Posição'),
        ),
        migrations.AlterUniqueTogether(
            name='pneu',
            unique_together={('caminhao', 'posicao')},
        ),
    ]
