# Generated by Django 6.0.4 on 2026-04-18 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0019_merge_0017_alter_cliente_documento_0018_carga_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='origem',
            field=models.CharField(blank=True, choices=[('Candeias/BA', 'Candeias - BA'), ('São Francisco do Conde/BA', 'São Francisco do Conde - BA'), ('Madre de Deus/BA', 'Madre de Deus - BA'), ('Suape/PE', 'Suape - PE')], default='', max_length=150, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='rota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.rota'),
            preserve_default=False,
        ),
    ]
