# Generated by Django 6.0.4 on 2026-04-10 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fretes', '0005_motorista_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='fretes.carga')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='fretes.motorista')),
            ],
            options={
                'verbose_name': 'Checklist de Viagem',
                'verbose_name_plural': 'Checklists de Viagem',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='DespesaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedagio', 'Pedágio'), ('alimentacao', 'Alimentação'), ('manutencao', 'Manutenção'), ('hospedagem', 'Hospedagem'), ('abastecimento', 'Abastecimento'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('comprovante', models.ImageField(blank=True, upload_to='despesas/%Y/%m/')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='fretes.carga')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='fretes.motorista')),
            ],
            options={
                'verbose_name': 'Despesa de Viagem',
                'verbose_name_plural': 'Despesas de Viagem',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AbastecimentoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(max_length=200)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_litro', models.DecimalField(decimal_places=4, max_digits=8)),
                ('foto_cupom', models.ImageField(upload_to='abastecimentos/%Y/%m/')),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimento', to='motorista_portal.despesaviagem')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('pneus', 'Pneus'), ('retrovisores', 'Retrovisores'), ('parabrisa', 'Para-brisa'), ('tanque', 'Tanque'), ('farois', 'Faróis'), ('freios', 'Freios'), ('documentos', 'Documentos'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='ok', max_length=10)),
                ('foto', models.ImageField(upload_to='checklist/%Y/%m/')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='motorista_portal.checklistviagem')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['categoria'],
            },
        ),
    ]
