# Generated by Django 6.0.4 on 2026-04-08 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150)),
                ('documento', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Local de carregamento',
                'verbose_name_plural': 'Locais de carregamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('observacoes', models.TextField(blank=True)),
                ('local_carregamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caminhoes', to='fretes.localcarregamento')),
                ('motorista_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caminhoes', to='fretes.motorista')),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_carga', models.DateField(default=django.utils.timezone.localdate)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_frete_litro', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_total_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.caminhao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.fornecedor')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.motorista')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.produto')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.rota')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['-data_carga', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('capacidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartimentos', to='fretes.caminhao')),
            ],
            options={
                'verbose_name': 'Compartimento',
                'verbose_name_plural': 'Compartimentos',
                'ordering': ['caminhao__placa', 'numero'],
                'unique_together': {('caminhao', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_por_litro', models.DecimalField(decimal_places=4, max_digits=10)),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_frete', to='fretes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_frete', to='fretes.produto')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_frete', to='fretes.rota')),
            ],
            options={
                'verbose_name': 'Tabela de frete',
                'verbose_name_plural': 'Tabelas de frete',
                'ordering': ['cliente__nome', 'produto__nome', 'rota__nome', '-vigencia_inicio'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'produto', 'rota', 'vigencia_inicio'), name='unique_tabela_frete_vigencia')],
            },
        ),
    ]
