# Generated by Django 6.0.4 on 2026-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='destino_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude destino'),
        ),
        migrations.AddField(
            model_name='rota',
            name='destino_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude destino'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='origem',
            field=models.CharField(choices=[('Candeias/BA', 'Candeias - BA'), ('São Francisco do Conde/BA', 'São Francisco do Conde - BA'), ('Suape/PE', 'Suape - PE')], max_length=150),
        ),
    ]
