# Generated by Django 6.0.4 on 2026-04-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0003_cargacompartimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.produto'),
        ),
    ]
