# Generated by Django 6.0.4 on 2026-04-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0005_motorista_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaminhaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('crlv', 'CRLV'), ('licenca_ambiental', 'Licença Ambiental'), ('antt', 'ANTT'), ('contrato_social', 'Contrato Social da Transportadora'), ('civ', 'CIV'), ('cipp', 'CIPP'), ('tacografo', 'Tacógrafo'), ('outros', 'Outros')], max_length=32)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('arquivo', models.FileField(upload_to='documentos_caminhao/%Y/%m/')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('observacoes', models.TextField(blank=True)),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='fretes.caminhao')),
            ],
            options={
                'verbose_name': 'Documento do caminhão',
                'verbose_name_plural': 'Documentos do caminhão',
                'ordering': ['caminhao__placa', 'tipo', 'descricao'],
            },
        ),
    ]
