# Generated by Django 6.0.4 on 2026-04-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0006_caminhaodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacompartimento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carga_compartimentos', to='fretes.cliente'),
        ),
    ]
