# Generated by Django 6.0.4 on 2026-04-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0007_cargacompartimento_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargacompartimento',
            name='cliente',
        ),
    ]
