# Generated by Django 6.0.4 on 2026-04-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0008_remove_cargacompartimento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='fretes.cliente', verbose_name='Cliente 01'),
        ),
        migrations.CreateModel(
            name='CargaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=2)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_adicionais', to='fretes.carga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_adicional', to='fretes.cliente')),
            ],
            options={
                'verbose_name': 'Cliente adicional',
                'verbose_name_plural': 'Clientes adicionais',
                'ordering': ['ordem'],
                'unique_together': {('carga', 'ordem')},
            },
        ),
    ]
