# Generated by Django 6.0.4 on 2026-04-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0016_pneu_status_alter_pneu_posicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
