# Generated by Django 6.0.4 on 2026-04-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0017_alter_carga_rota_alter_cliente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='origem',
            field=models.CharField(blank=True, choices=[('Candeias/BA', 'Candeias - BA'), ('São Francisco do Conde/BA', 'São Francisco do Conde - BA'), ('Madre de Deus/BA', 'Madre de Deus - BA'), ('Suape/PE', 'Suape - PE')], max_length=150, verbose_name='Origem'),
        ),
    ]
