# Generated by Django 6.0.4 on 2026-04-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0017_alter_cliente_documento'),
        ('fretes', '0018_carga_origem'),
    ]

    operations = [
    ]
