# Generated by Django 6.0.4 on 2026-04-18 23:24

from django.db import migrations, models


def migrate_recapado_to_recapagem(apps, schema_editor):
    Pneu = apps.get_model('fretes', 'Pneu')
    Pneu.objects.filter(recapado=True).update(recapagem='1')


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0020_alter_carga_origem_alter_carga_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneu',
            name='recapagem',
            field=models.CharField(blank=True, choices=[('', 'Não recapado'), ('1', '1° Recapeamento'), ('2', '2° Recapeamento'), ('3', '3° Recapeamento')], default='', max_length=1, verbose_name='Recapeamento'),
        ),
        migrations.RunPython(migrate_recapado_to_recapagem, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pneu',
            name='recapado',
        ),
    ]
